POST http://localhost:3002/register
Content-type: application/json

{
    "usuario":"test2",
    "email":"test2@test.com",
    "password":"test2"
}

### 
GET http://localhost:3002/show_users

###
GET http://localhost:3002/user/sergio